### ISSUE TITLE
Move the repository to the typed-mxgraph organization

### ISSUE THREAD

**Issue by tbouffard** [typed-mxgraph/typed-mxgraph-example-bundled-with-rollup#2]
@hungtcs hi, what do you think about moving this example repository directly to the https://github.com/typed-mxgraph GitHub organization?
This will provide an alternative vanilla Typescript example to the already existing WebPack example: https://github.com/typed-mxgraph/typed-mxgraph-demo

In the meantime, we could also recreate framework related projects (Angular, React, ...) as we had for the old https://github.com/hungtcs/mxgraph-type-definitions:
- https://github.com/hungtcs/react-with-mxgraph
- https://github.com/hungtcs/angular-with-mxgraph

**Comment by hungtcs** [comment]
Hi, @tbouffard, this is a good idea, I would be very happy to receive this repository, and I will create some starter projects about angular and react later.

**Comment by tbouffard** [comment]
Ok nice!
I can change the repository name which is very long but at least it describes what the repository does. Do you have any wish on that topic? we can rename it later as well.
My only request would be to keep an 'Admin' role on this repository to be able to maintain everything on it. This will avoid adding more work on your side too.

About the react and angular starters, I could help on this topic (at least review and test) but I have limited knowledges on these topics as I don't use them on daily basis.

**Comment by hungtcs** [comment]
Of course @tbouffard, I have changed the default member repository permissions of typed-mxgraph organization to write, now you should have permissions for all repositories, if not, please contact me to check.
And I think there is no harm in having a long name, we can define the naming convention of the sample projects, my current thinking is:
```
typed-mxgraph-example-[describe]
```
- typed-mxgraph-example-react
- typed-mxgraph-example-angular
- typed-mxgraph-example-vanilla-typescript
- typed-mxgraph-example-bundled-with-rollup
- typed-mxgraph-example-bundled-with-webpack
- and more...

What do you think about this naming conventions, if possible, I will rename [typed-mxgraph-demo](https://github.com/typed-mxgraph/typed-mxgraph-demo) to `typed-mxgraph-example-bundled-with-webpack`, and this repository will would be `typed-mxgraph-example-bundled-with-rollup`.

**Comment by tbouffard** [comment]
👍🏿 for your naming convention and ok to rename this repository into `typed-mxgraph-example-bundled-with-rollup`
I will trigger the transfer ownership to the `typed-mxgraph` organization soon.

**Comment by tbouffard** [comment]
Repository has been renamed.
Transfer is in progress.

![image](https://user-images.githubusercontent.com/27200110/105031404-91d04e80-5a55-11eb-86d1-503f02c65a1e.png)

**Comment by tbouffard** [comment]
Transfer done

![image](https://user-images.githubusercontent.com/27200110/105031634-df4cbb80-5a55-11eb-8319-3a432b33f47b.png)

**Comment by hungtcs** [comment]
@tbouffard I have renameed `typed-mxgraph-demo` to `typed-mxgraph-example-bundled-with-webpack`, and update readme.

**Comment by tbouffard** [comment]
Task completed so closing.
